name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Install compiler
      run: |
        ln -s ../tibasic/tibasic
        cd ..
        git clone https://github.com/dmfrodrigues/tibasic.git
        cd tibasic
        make
    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Build programs
      run: |
        make
    - name: Upload programs
      uses: actions/upload-artifact@v2
      with:
        name: programs
        path: |
          ASMBATTE.8xp
          CHAOS.8xp
          ISPRIME.8xp
          JULIA.8xp
          KOCH.8xp
          LANGTON.8xp
          LWERCASE.8xp
          PRIMESIE.8xp
          SIERPINS.8xp
          SNAKE.8xp
